### ISSUE TITLE
exportRecords $filterLogic parameter is marked as array type but should probably be a string

### ISSUE THREAD

**Issue by gadeynebram** [IUREDCap/phpcap#1]
Hi,

In the method specification $filterLogic is marked as an array type parameter. Could it be that this should be string?

https://github.com/IUREDCap/phpcap/blob/e557781aa4cfae8c4531d3e2cd81b078714d6c2a/src/RedCapProject.php#L1029

In exportRecords I see that the method calls processFilterLogicArgument.

https://github.com/IUREDCap/phpcap/blob/e557781aa4cfae8c4531d3e2cd81b078714d6c2a/src/RedCapProject.php#L1114

This on it's turn checks for the parameter to be of type "string".

https://github.com/IUREDCap/phpcap/blob/e557781aa4cfae8c4531d3e2cd81b078714d6c2a/src/RedCapProject.php#L2345-L2358

**Comment by mullen2** [comment]
Hi Bram,

Thanks for pointing that out. We will try to get that corrected in the next release.

Jim

**Comment by mullen2** [comment]
Fixed in release 1.1.0.
