### ISSUE TITLE
Deprecation warning on PHP 8

### ISSUE THREAD

**Issue by BlairCooper** [IUREDCap/phpcap#11]
Using PHPCap on PHP 8 generates a deprecation warning because $apiUrl is not defined as a class member in the RedCapProject class.

"PHP Deprecated:  Creation of dynamic property IU\PHPCap\RedCapProject::$apiUrl is deprecated"

**Comment by mullen2** [comment]
@BlairCooper, thanks for letting me know. This should be fixed in the latest version (1.4.2).
