### ISSUE TITLE
Return type typo in RedCapProject::exportInstrumentEventMappings()

### ISSUE THREAD

**Issue by BlairCooper** [IUREDCap/phpcap#12]
The return type for exportInstrumentEventMappings() is listed as 'arrray', three 'r's.

While generally not a big deal, this does cause a problem for static analysis tools like PHPStan which complains with:
"... expects array, UI\PHPCap\arrray given"

**Comment by mullen2** [comment]
@BlairCooper Thanks for letting me know. I have fixed this, and the fix will be in the next release.

**Comment by BlairCooper** [comment]
Curious if there is a timeframe for the next release?

**Comment by mullen2** [comment]
@BlairCooper There is no timeframe at this point, but looking at my schedule, I don't see a new release happening until next year.

**Comment by BlairCooper** [comment]
Looks like this fix was included in version 1.5.2. Thanks.
