### ISSUE TITLE
Which REDCap version was phpcap written for / is compatible with?

### ISSUE THREAD

**Issue by zaliqarosli** [IUREDCap/phpcap#7]
Hi, I am not able to find information on what versions of REDCap this API is compatible with. I'm new to REDCap so I'm not sure how much their API varies version to version. thanks!

**Comment by aarenson** [comment]
Typically, the most recent version of PHPCap supports all API methods available from the most recent LTS version of REDCap and any previous versions of REDCap. There may be a lag, at times, between PHPCap catching up to the most recent LTS.

**Comment by zaliqarosli** [comment]
would be useful to include the latest LTS version of REDCap in the docs or with each release of PHPCap in the release notes, just so we know where there is a lag

**Comment by zaliqarosli** [comment]
i just saw that you have a REDCap version listed under the pre-requisites in your [user guide](https://iuredcap.github.io/phpcap/UserGuide1.html). that should suffice! closing this issue
